### PR TITLE
SwiftEval: Load tests bundle if exists.

### PR DESCRIPTION
**Pull request by byohay**
Previously, when running tests through injection, if the test would have depended upon a symbol that's in the tests bundle, it would give an undefined symbol error. This commit solves this by loading the tests bundle if it exists, which allows for much better support when loading new test files through injection.

Notes:
- Right now the tests bundle is loaded regardless of the file being injected - I couldn't figure whether I can get the name of the file from `loadAndInject` function. 
- I only tested it on iOS, with standalone mode and with the mac app.

### CODE REVIEW

**Comment by johnno1962** [comment]
Awesome! I'll take your word for it working and I can roll a new release candidate. Thanks for wading through some pretty eccentric code to work this out. Is it worth combining the two methods to be able to load than one .xctest bundle? Would that ever happen? I wouldn't worry about filtering by file name, these loads only happen once.

**Comment by johnno1962** [comment]
I went ahead, merged and rolled a new release candidate with your change. Can you check it for me please? https://github.com/johnno1962/InjectionIII/releases/tag/4.5.3. Thanks very much taking the time to fix this.

**Comment by byohay** [comment]
@johnno1962 sorry for the delay, it works perfectly 😄

**Comment by johnno1962** [comment]
It's a bit of a novelty to get a PR on SwiftEval.swift. I wonder why 😄? Thanks again @byohay.

**Pull request merged**
